config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  resources :users do
    get 'shows/behind', to: 'shows#behind'
    resources :watchlists 
    resources :shows, only: [:index]
  end
  resources :watchlists
  resources :listings, only: [:destroy]
  resources :shows do
    resources :listings, except: [:index, :destroy]
  end
  resources :genres, only: [:index, :show]
  resources :channels, only: [:index, :show]
  get '/search', to: 'shows#search'
  get '/auth/facebook/callback', to: 'users#facebook_login'
  get '/auth/:google_oauth2/callback' => 'users#create_google'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
end

app/models/watchlist.rb
class Watchlist < ApplicationRecord
    belongs_to :user, dependent: :destroy
    has_many :listings, dependent: :destroy
    has_many :shows, through: :listings
  
    validates :name, presence: true,  format: { without: /[0-9]/, message: "does not allow numbers" }
  
    before_destroy :destroy_listings
  
    private
    def destroy_listings
      self.listings.each do |listing|
        listing.destroy
      end
    end
  end

app/controllers/watchlists_controller.rb
class WatchlistsController < ApplicationController
    before_action :require_login
    before_action :set_user_watchlist, only: [:show, :edit, :update, :destroy]
    before_action :set_user
  
    def index
      @watchlists = current_user.watchlists
      @favorites = current_user.favorite_shows
    end
  
    def new
      @watchlist = Watchlist.new
    end
  
    def create
      @watchlist = @user.watchlists.build(watchlist_params)
      if @watchlist.save
        redirect_to watchlist_path(@watchlist)
        flash[:message] = "New Watchlist Created!"
      else
        render :new
      end
    end
  
    def show
      @shows = @watchlist.shows
    end
  
    def edit
    end
  
    def update
      @watchlist.update(watchlist_params)
      if @watchlist.save
        redirect_to watchlist_path(@watchlist)
        flash[:message] = "#{@watchlist.name} updated!"
      else
        render :edit
      end
    end
  
    def destroy
      if @watchlist
        @watchlist.destroy
        redirect_to watchlists_path
        flash[:message] = "Your watchlist has been deleted"
      else
        render :show
        flash[:danger] = "This watchlist could not be deleted"
      end
    end
  
    private
    def watchlist_params
      params.require(:watchlist).permit(:name, :description, :user_id)
    end
  
    def set_user_watchlist
      @watchlist = Watchlist.find_by(id: params[:id])
      unless @watchlist.user == current_user
        flash[:danger] = "This is not your watchlist!"
        redirect_to watchlists_path
      end
    end
  
    def set_user
      @user = User.find_by(id: params[:user_id])
    end
  end

app/helpers/watchlists_helper.rb
module WatchlistsHelper
end

app/views/watchlists/_form.html.erb
<% if watchlist.errors.any? %>
<div class="alert alert-danger" role="alert">
  <ul>
      <% watchlist.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
  </ul>
</div>
<% end %>

<%= form_for [user, watchlist] do |f| %>
  <strong><%= f.label :name %></strong>
  <%= f.text_field :name, class:"form-control" %><br>
  <strong><%= f.label :description %></strong>
  <%= f.text_area :description, class:"form-control" %><br>
  <%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/watchlists/edit.html.erb
<% content_for :header do %>
    <h1>Update <%= @watchlist.name %> Watchlist</h1>
  <% end %>
  
  <% content_for :vertical_nav do %>
    <ul class="nav flex-column">
      <li class="nav-item mb-3">
        <%= button_to "Back to Watchlists", user_watchlists_path(current_user), :method => "get", class: "btn btn-info btn-block" %>
      </li>
    </ul>
  <% end %>
  
  <% content_for :content do %>
    <%= render partial: "form", locals: {user: @user, watchlist: @watchlist} %>
  <% end %>

app/views/watchlists/index.html.erb
<% content_for :header do %>
    <h1><%= current_user.username %>'s Watchlists</h1>
  <% end %>
  
  <% content_for :vertical_nav do %>
    <ul class="nav flex-column">
      <li class="nav-item mb-3">
        <%= button_to "Create a new Watchlist", new_user_watchlist_path(current_user), :method => "get", class: "btn btn-info btn-block" %>
      </li>
      <li class="nav-item mb-3">
        <%= button_to "Add a Show", shows_path, :method => "get", class: "btn btn-info btn-block" %>
      </li>
      <li class="nav-item">
        <%= form_tag(user_shows_behind_path(current_user), method: "get") do %>
          <%= submit_tag("Shows I'm Behind On", class: "btn btn-warning btn-block") %>
        <% end %>
      </li>
    </ul>
  <% end %>
  
  
  <% content_for :content do %>
    <% if @watchlists.count == 0 %>
      <p><center>You don't have any watchlists! <%= link_to "Create One", new_user_watchlist_path(current_user) %> to start adding shows!</center></p>
    <% else %>
      <% @watchlists.each do |watchlist| %>
        <div class="card border-info mb-3">
          <div class="card-body">
            <h5 class="card-title"><%= link_to watchlist.name, user_watchlist_path(current_user, watchlist) %></h5>
            <p class="card-text"><%= watchlist.description %></p>
          </div>
        </div>
      <% end %>
    <% end %>
  <% end %>
  
  <% content_for :sidebar do %>
    <p>Favorite Shows</p>
    <% @favorites.each do |show| %>
      <p> <%= link_to show.title, show_path(show) %></p>
    <% end %>
    <%= button_to "See All of My Shows", user_shows_path(current_user), :method => "get", class: "btn btn-info" %>
  <% end %>

app/views/watchlists/new.html.erb
<% content_for :header do %>
    <h1>Create a New Watchlist</h1>
  <% end %>
  
  <% content_for :vertical_nav do %>
    <ul class="nav flex-column">
      <li class="nav-item mb-3">
        <%= button_to "Back to Watchlists", user_watchlists_path(current_user), :method => "get", class: "btn btn-info btn-block" %>
      </li>
    </ul>
  <% end %>
  
  <% content_for :content do %>
    <%= render partial: "form", locals: {user: @user, watchlist: @watchlist} %>
  <% end %>

app/views/watchlists/show.html.erb
<% content_for :header do %>
  
    <h1><%= @watchlist.name %></h1>
    <p><em><%= @watchlist.description %></em></p>
  <% end %>
  
  <% content_for :vertical_nav do %>
    <ul class="nav flex-column">
      <li class="nav-item mb-3">
        <%= button_to "Edit this Watchlist", edit_user_watchlist_path(current_user, @watchlist), :method => "get", class: "btn btn-warning btn-block" %>
      </li>
      <li class="nav-item mb-3">
        <%= button_to "Back to All Watchlists", user_watchlists_path(current_user), :method => "get", class: "btn btn-info btn-block" %>
      </li>
      <li class="nav-item">
        <%= button_to "Add Shows", shows_path, :method => "get", class: "btn btn-info btn-block" %>
      </li>
    </ul>
  <% end %>
  
  <% content_for :content do %>
    <% @shows.each do |show| %>
        <div class="card mb-3">
          <h5 class="card-header"><%= link_to show.title, show_path(show) %></h5>
          <ul class="list-group list-group-flush">
            <li class="list-group-item">Channel: <%= show.channel.name %></li>
            <li class="list-group-item">Season: <%= show.current_season %></li>
          </ul>
        </div>
    <% end %>
  <% end %>
  
  <% content_for :sidebar do %>
    <%= form_tag(watchlist_path, method: "delete") do %>
      <%= submit_tag("Delete Watchlist", class: "btn btn-danger btn-block") %>
    <% end %>
  <% end %>