config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  resources :users do
    get 'shows/behind', to: 'shows#behind'
    resources :watchlists 
    resources :shows, only: [:index]
  end
  resources :watchlists
  resources :listings, only: [:destroy]
  resources :shows do
    resources :listings, except: [:index, :destroy]
  end
  resources :genres, only: [:index, :show]
  resources :channels, only: [:index, :show]
  get '/search', to: 'shows#search'
  get '/auth/facebook/callback', to: 'users#facebook_login'
  get '/auth/:google_oauth2/callback' => 'users#create_google'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
end

app/models/listing.rb
class Listing < ApplicationRecord
    belongs_to :watchlist
    belongs_to :show
    belongs_to :user
  
    validates :user_season, presence: true, numericality: { greater_than: 0 }
    validates :watchlist_id, uniqueness: { scope: :show_id }, :on => :create
    validate :user_season_vs_current_season
  
    def user_season_vs_current_season
      if user_season.present? && user_season > show.current_season
        errors.add(:user_season, "can't be ahead of the show's Season #{show.current_season}")
      end
    end
  end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
    before_action :require_login
    before_action :set_listing, only: [:edit, :update, :destroy]
   

    def new
      @listing = Listing.new
      @listing.show = Show.find_by(id: params[:show_id])
    end
  
    def create
      @listing = Listing.new(listing_params)
      @listing.show = Show.find_by(id: params[:show_id])
      if @listing.save
        flash[:message] = "#{@listing.show.title} has been added to your watchlist"
        redirect_to show_path(@listing.show)
      else
        render :new
      end
    end
  
    def edit
    end
  
    def update
      @listing.update(listing_params)
      if @listing.save
        flash[:message] = "#{@listing.show.title} listing has been updated"
        redirect_to show_path(@listing.show)
      else
        render :edit
      end
    end
  
    def destroy
      if @listing
        @listing.destroy
        flash[:message] = "The show has been removed from your watchlist"
        redirect_to watchlists_path
      else
        flash[:danger] = "The show could not be removed"
        render 'shows/show'
      end
    end
  
    private
    def listing_params
      params.require(:listing).permit(:watchlist_id, :user_id, :user_status, :user_season, :fav)
    end
  
    def set_listing
      @listing = Listing.find_by(id: params[:id])
    end
  end

app/views/listings/_details.html.erb
<% listings.each do |listing| %>
    <div class="card card-sm mb-3">
      <h5 class="card-header"><%= link_to listing.watchlist.name, user_watchlist_path(current_user, listing.watchlist) %></h5>
      <div class="card-body">
        <p><strong>Your Status</strong>:<br>
          <%= listing.user_status %><br>
        <strong>Your Season</strong>: <%= listing.user_season %></p>
        <%= button_to "Edit Show Listing", edit_show_listing_path(show, listing), :method => "get", class: "btn btn-warning btn-sm btn-block" %>
        <%= form_for listing, method: :delete do |f| %>
          <%= f.submit "Delete Show Listing", class:"btn btn-sm btn-danger btn-block" %>
        <% end %>
      </div>
    </div>
  <% end %>

app/views/listings/_form.html.erb
<% if listing.errors.any? %>
  <div class="alert alert-danger" role="alert">
    <ul>
    <% listing.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_for [show, listing] do |f| %>
  <strong><%= f.label :watchlist %></strong>
  <%= f.collection_select :watchlist_id, alphebetize(current_user.watchlists), :id, :name %><br>
  <strong><%= f.label :user_status %></strong>
  <%= f.text_field :user_status, class:"form-control" %><br>
  <strong><%= f.label :user_season %></strong>
  <%= f.number_field :user_season, class:"form-control" %><br>
  <%= f.check_box :fav %> <strong>Fav?</strong> <br>
  <%= f.hidden_field :user_id, value: current_user.id %><br>
  <%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/listings/edit.html.erb
<% content_for :header do %>
    <h1>Edit <%= @listing.show.title %> on '<%= @listing.watchlist.name %>' Watchlist</h1>
  <% end %>
  
  <% content_for :vertical_nav do %>
    <ul class="nav flex-column">
      <li class="nav-item mb-3">
        <%= button_to "Back to #{@listing.show.title}", show_path(@listing.show), :method => "get", class: "btn btn-info btn-block" %>
      </li>
    </ul>
  <% end %>
  
  <% content_for :content do %>
    <%= render partial: "form", locals: {listing: @listing, show: @listing.show} %>
  <% end %>

app/views/listings/new.html.erb
<% content_for :header do %>
    <h1>Add <%= @listing.show.title %> to Your Watchlist</h1>
  <% end %>
  
  <% content_for :vertical_nav do %>
    <ul class="nav flex-column">
      <li class="nav-item mb-3">
        <%= button_to "Back to #{@listing.show.title}", show_path(@listing.show), :method => "get", class: "btn btn-info btn-block" %>
      </li>
    </ul>
  <% end %>
  
  <% content_for :content do %>
    <%= render partial: "form", locals: {listing: @listing, show: @listing.show} %>

  <% end %>