config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  resources :users do
    get 'shows/behind', to: 'shows#behind'
    resources :watchlists 
    resources :shows, only: [:index]
  end
  resources :watchlists
  resources :listings, only: [:destroy]
  resources :shows do
    resources :listings, except: [:index, :destroy]
  end
  resources :genres, only: [:index, :show]
  resources :channels, only: [:index, :show]
  get '/search', to: 'shows#search'
  get '/auth/facebook/callback', to: 'users#facebook_login'
  get '/auth/:google_oauth2/callback' => 'users#create_google'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
end

app/views/shared/_alerts.html.erb
<% flash.keys.each do |k| %>
    <% if k == "danger" %>
      <div class="alert alert-danger" role="alert">
    <% else %>
      <div class="alert alert-primary alert-dismissible fade show" role="alert">
    <% end %>
        <%= flash[k] %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
  <% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <img src="/images/play-icon.png" width="30" height="30" class="d-inline-block alignt-top">
  <%= link_to "TV-Shows", user_watchlists_path(current_user), class: "navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item px-3">
        <%= link_to "Watchlists", user_watchlists_path(current_user), class: "nav-link" %>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Shows
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to "All Shows", shows_path, class: "dropdown-item" %>
          <%= link_to "My Shows", user_shows_path(current_user), class: "dropdown-item" %>
        </div>
      </li>
    </ul>
    <ul class="navbar-nav ml-auto">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <%= current_user.username %>
        </a>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <%= link_to "My Account", user_path(current_user), class: "dropdown-item" %>
          <%= link_to "Logout", logout_path, class: "dropdown-item" %>
        </div>
      </li>
    </ul>
  </div>
</nav>