config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  resources :users do
    get 'shows/behind', to: 'shows#behind'
    resources :watchlists 
    resources :shows, only: [:index]
  end
  resources :watchlists
  resources :listings, only: [:destroy]
  resources :shows do
    resources :listings, except: [:index, :destroy]
  end
  resources :genres, only: [:index, :show]
  resources :channels, only: [:index, :show]
  get '/search', to: 'shows#search'
  get '/auth/facebook/callback', to: 'users#facebook_login'
  get '/auth/:google_oauth2/callback' => 'users#create_google'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
end

app/models/show.rb
class Show < ApplicationRecord
    has_many :listings, dependent: :destroy
    has_many :watchlists, through: :listings
    has_many :users, through: :listings
    has_many :show_genres,  dependent: :destroy
    has_many :genres, through: :show_genres
    belongs_to :channel, counter_cache: true
  
    validates :title, presence: true, uniqueness: { scope: :channel_id } # Validates uniqueness of title and channel
    validates :current_season, presence: true, numericality: { greater_than: 0 }
  
    scope :search, -> (query) { where("title LIKE ?", "%" + query + "%") if query.present?}
    scope :behind_on, -> (user_id) { joins(:listings).where('shows.current_season > listings.user_season').where(listings: {user_id: user_id}).uniq }
  
    def channel_attributes=(channel_attributes)
      channel_attributes.values.each do |channel_attribute|
        unless channel_attribute.blank?
          channel = Channel.find_or_create_by(name: channel_attribute)
          self.channel = channel
        end
      end
    end
  
    def genres_attributes=(genre_attributes)
      genre_name = genre_attributes["0"]["name"]
      unless genre_name.blank?
        genre = Genre.find_or_create_by(name: genre_name)
        self.genres << genre
      end
    end
  
    def shows_watchlists_by_user(user_id)
      self.listings.where(user_id: user_id)
    end
  end

app/controllers/shows_controller.rb
class ShowsController < ApplicationController
    before_action :require_login
    before_action :set_show, only: [:show, :edit, :update, :destroy]
    before_action :created_by_current_user, only: [:edit, :update]
    before_action :by_current_user, only: [:destroy]
    helper_method :current_user
  
    def index
      @user = User.find_by(id: params[:user_id])
      if @user
        @shows = @user.shows.uniq
      else
        @shows = Show.all
      end
    end
  
    def show
      @listings = @show.shows_watchlists_by_user(current_user.id)
    end
  
    def new
      @show = Show.new
      @listings = @show.listings.build
    end
  
    def create
      @show = Show.new(show_params)
      if @show.save
        flash[:message] = "#{@show.title} has been created"
        redirect_to show_path(@show)
      else
        render :new
      end
    end
  
    def edit
    end
  
    def update
      @show.update(show_params)
      if @show.save
        flash[:message] = "#{@show.title} has been updated"
        redirect_to show_path(@show)
      else
        render :edit
      end
    end
    
      def search
        @shows = Show.search(params[:query])
        render :index
      end
  
    def behind
      @shows = Show.behind_on(current_user.id)
      render :index
    end

    def destroy 
      @show.destroy
      redirect_to shows_path
    end
  
    private
    def show_params
      params.require(:show).permit( :title,
                                    :description,
                                    :channel_id,
                                    :day,
                                    :time,
                                    :current_season,
                                    :created_by,
                                    genre_ids:[],
                                    genres_attributes:[:name],
                                    channel_attributes:[:name])
    end
  
    def set_show
      @show = Show.find_by(id: params[:id])
    end
  
    def created_by_current_user
      unless @show.created_by == current_user.id
        flash[:danger] = "You cannot edit this show because you did not create it!"
        redirect_to show_path(@show)
      end
    end
    def by_current_user
      unless @show.created_by == current_user.id
        flash[:danger] = "You cannot delete this show because you did not create it!"
        redirect_to show_path(@show)
      end
    end
  end

app/helpers/shows_helper.rb
module ShowsHelper
    def watchlist_options(listings, show)
      if @listings.count > 0
        render :partial => "listings/details", :locals => {:listings => listings, :show => show}
      else
        "None"
      end
    end
  end
  

app/views/shows/_form.html.erb
<% if @show.errors.any? %>
  <div class="alert alert-danger" role="alert">
    <ul>
    <% @show.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_for(show) do |f| %>
  <strong><%= f.label :title %></strong>
  <%= f.text_field :title, class:"form-control" %><br>

  <strong><%= f.label "Show Description" %></strong>
  <%= f.text_area :description, class:"form-control" %><br>

  <div class="form-group">
    <strong><%= f.label :channel %></strong><br>
    <%= f.collection_select :channel_id, alphebetize(Channel.all), :id, :name, :include_blank => true%> or new: 
    <%= f.fields_for :channel_attributes do |channel_fields| %>
      <%= channel_fields.text_field :name %>
    <% end %>
  </div>

  <strong><%= f.label :current_season %><br></strong>
  <%= f.number_field :current_season, class:"form-control" %><br>

  <div class="form-group">
    <strong><%= f.label :genre %></strong><br>
    <%= f.collection_check_boxes(:genre_ids, alphebetize(Genre.all), :id, :name) do |b| %>
      <div class="form-check form-check-inline">
        <%= b.check_box(class: "form-check-input") %>
        <%= b.object.name %>
      </div>
    <% end %>
    or new:
    <%= f.fields_for :genres, show.genres.build do |genre_fields| %>
      <%= genre_fields.text_field :name %>
    <% end %>
  </div>

  <strong><%= f.label :day %></strong>
  <%= f.text_field :day, class:"form-control" %>
  <br>

  <strong><%= f.label :time %></strong>
  <%= f.text_field :time, class:"form-control" %><br>

  <%= f.hidden_field :created_by, value: current_user.id %>
  <%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/shows/_shows.html.erb
<table class="table table-striped table-hover table-light">
  <thead>
    <tr>
      <th scope="col">Title</th>
      <th scope="col">Channel</th>
      <th scope="col">Seasons</th>
      <th scope="col">Genres</th>
    </tr>
  </thead>
  <tbody>
    <% alphebetize(shows).each do |show| %>
      <tr>
        <th scope="row"><%= link_to show.title, show_path(show) %></th>
        <td><%= show.channel.name%></td>
        <td><%= show.current_season %></td>
        <td><%= show.genres.map { |genre| genre.name }.join(', ') %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/shows/edit.html.erb
<% content_for :header do %>
    <h1>Edit <%= @show.title %></h1>
  <% end %>
  
  <% content_for :vertical_nav do %>
    <ul class="nav flex-column">
      <li class="nav-item mb-3">
        <%= button_to "Back to #{@show.title}", show_path(@show), :method => "get", class: "btn btn-info btn-block" %>
      </li>
      <li class="nav-item mb-3">
        <%= button_to "View All Shows", shows_path, :method => "get", class: "btn btn-info btn-block" %>
      </li>
    </ul>
  <% end %>
  
  <% content_for :content do %>
    <%= render partial: "form", locals: {show: @show} %>
  <% end %>

app/views/shows/index.html.erb
<% content_for :header do %>
  <h1><%= link_to "Browse Shows", shows_path %></h1>
<% end %>

<% content_for :vertical_nav do %>
<ul class="nav flex-column">
  <li class="nav-item mb-3">
    <%= button_to "Add New Show", new_show_path, :method => "get", class: "btn btn-info btn-block" %>
  </li>
  <li class="nav-item">
    <%= button_to "Back to my Watchlists", user_watchlists_path(current_user), :method => "get", class: "btn btn-info btn-block" %>
  </li>
</ul>
<% end %>

<% content_for :content do %>
  <%= render partial: "shows", locals: {shows: @shows} %>
<% end %>

<% content_for :sidebar do %>
  <%= form_tag("/search", method: "get") do %>
    <%= label_tag :query, "Search by Title:" %>
    <%= text_field_tag :query, "", class:"form-control" %>
    <%= submit_tag "Search", class: "btn btn-sm btn-secondary" %>
  <% end %>
  <br>
  <p>Browse By:
  <div class="btn-group" role="group">
    <%= button_to "Genre", genres_path, :method => "get", class: "btn btn-outline-secondary" %>
    <%= button_to "Channel", channels_path, :method => "get", class: "btn btn-outline-secondary" %>
  </div>
  </p>
<% end %>

app/views/shows/new.html.erb
<% content_for :header do %>
    <h1>Create a New Show</h1>
  <% end %>
  
  <% content_for :vertical_nav do %>
    <ul class="nav flex-column">
      <li class="nav-item mb-3">
        <%= button_to "Back to Shows", user_shows_path(current_user), :method => "get", class: "btn btn-info btn-block" %>
        
      </li>
    </ul>
  <% end %>
  
  <% content_for :content do %>
    <%= render partial: "form", locals: {show: @show} %>
  <% end %>
  
  
  

app/views/shows/show.html.erb
<% content_for :header do %>
  
    <h1><%= @show.title %></h1>
  <% end %>
  
  <% content_for :vertical_nav do %>
    <ul class="nav flex-column">
      <li class="nav-item mb-3">
        <%= button_to "Back to Shows", shows_path, :method => "get", class: "btn btn-info btn-block" %>
      </li>
      <% if @show.created_by == current_user.id %>
        <li class="nav-item mb-3">
          <%= button_to "Update show details", edit_show_path(@show), :method => "get", class: "btn btn-info btn-block" %>
        </li>
      <% end %>
      <% if @show.created_by == current_user.id %>
      <li class="nav-item mb-3">
          <%= button_to "Delete Show", show_path , :method => "delete", class: "btn btn-info btn-block" %>
        </li>
      <% end %>

      <li class="nav-item">
        <%= button_to "Add to A Watchlist", new_show_listing_path(@show), :method => "get", class: "btn btn-info btn-block" %>
      </li>
    </ul>
  
  <% end %>

  
  
  <% content_for :content do %>

    <p><%= @show.description %></p>
    <p><strong>Channel</strong>: <%= link_to @show.channel.name, channel_path(@show.channel) %></p>
    <p><strong>Current Season</strong>: <%= @show.current_season %></p>
    <p><strong>Genres</strong>: <%= @show.genres.map { |genre| link_to(genre.name, genre_path(genre)) }.join(', ').html_safe %></p>
    <p><strong>Day</strong>: <%= @show.day %></p>
    <p><strong>Time</strong>: <%= @show.time %></p>

   <% end %>

   <% content_for :sidebar do %>
    <h4>My Watchlists</h4>
    <%= watchlist_options(@listings, @show) %>
  <% end %>
  